// <auto-generated />
namespace APP_A
{
    partial class MainForm
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.TextBox textLog;
        private System.Windows.Forms.NumericUpDown numericPort;
        private System.Windows.Forms.CheckBox checkOutput;
        private System.Windows.Forms.Button buttonSetOutput;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.textLog = new System.Windows.Forms.TextBox();
            this.numericPort = new System.Windows.Forms.NumericUpDown();
            this.checkOutput = new System.Windows.Forms.CheckBox();
            this.buttonSetOutput = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(this.numericPort)).BeginInit();
            this.SuspendLayout();
            // 
            // textLog
            // 
            this.textLog.Location = new System.Drawing.Point(12, 12);
            this.textLog.Multiline = true;
            this.textLog.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.textLog.Size = new System.Drawing.Size(360, 150);
            this.textLog.TabIndex = 0;
            // 
            // numericPort
            // 
            this.numericPort.Location = new System.Drawing.Point(12, 180);
            this.numericPort.Maximum = new decimal(new int[] { 255, 0, 0, 0 });
            this.numericPort.Name = "numericPort";
            this.numericPort.Size = new System.Drawing.Size(120, 23);
            this.numericPort.TabIndex = 1;
            // 
            // checkOutput
            // 
            this.checkOutput.Location = new System.Drawing.Point(12, 210);
            this.checkOutput.Name = "checkOutput";
            this.checkOutput.Size = new System.Drawing.Size(100, 24);
            this.checkOutput.Text = "出力ON/OFF";
            this.checkOutput.UseVisualStyleBackColor = true;
            // 
            // buttonSetOutput
            // 
            this.buttonSetOutput.Location = new System.Drawing.Point(150, 180);
            this.buttonSetOutput.Name = "buttonSetOutput";
            this.buttonSetOutput.Size = new System.Drawing.Size(100, 23);
            this.buttonSetOutput.Text = "出力設定";
            this.buttonSetOutput.UseVisualStyleBackColor = true;
            this.buttonSetOutput.Click += new System.EventHandler(this.buttonSetOutput_Click);
            // 
            // MainForm
            // 
            this.ClientSize = new System.Drawing.Size(400, 250);
            this.Controls.Add(this.textLog);
            this.Controls.Add(this.numericPort);
            this.Controls.Add(this.checkOutput);
            this.Controls.Add(this.buttonSetOutput);
            this.Name = "MainForm";
            this.Text = "APP_A";
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.MainForm_FormClosed);
            ((System.ComponentModel.ISupportInitialize)(this.numericPort)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
    }
}
